# PostgreSQL Client Authentication (local dev)
# trust — без пароля, допустимо т.к. порт 5432 открыт только на localhost
# Unix-сокеты внутри контейнера тоже trust

local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust
host    all             all             172.16.0.0/12           trust
host    all             all             192.168.0.0/16          trust
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust
