apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    database: "sportgid-logs-*"
    editable: false
    jsonData:
      esVersion: "8.0.0"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
